---

- name: Ensure distribution is LTS or cvmfs_apt_distribution is set
  assert:
    that: >-
      (ansible_distribution == 'Ubuntu' and 'LTS' in (ansible_lsb.distribution | default(''))) or
      (ansible_distribution == 'Debian' and ansible_distribution_version != 'n/a') or
      (cvmfs_apt_distribution is defined)
    fail_msg: "Unsupported distribution: {{ ansible_distribution }} {{ ansible_distribution_release }}, please set cvmfs_apt_distribution"
    success_msg: "Distribution OK"

- name: Install apt dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates

- name: Remove old CernVM apt repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/cernvm.list.list
    state: absent

- name: Remove old CernVM GPG key from legacy keyring
  ansible.builtin.apt_key:
    url: https://cvmrepo.web.cern.ch/cvmrepo/apt/cernvm.gpg
    state: absent
  ignore_errors: true

- name: Download CernVM GPG key
  ansible.builtin.get_url:
    url: https://cvmrepo.web.cern.ch/cvmrepo/apt/cernvm.gpg
    dest: /usr/share/keyrings/cernvm.gpg
    mode: "0644"

- name: Configure CernVM apt repository
  ansible.builtin.apt_repository:
    filename: cernvm
    mode: "0644"
    repo: deb [signed-by=/usr/share/keyrings/cernvm.gpg] https://cvmrepo.web.cern.ch/cvmrepo/apt/ {{ cvmfs_apt_distribution | default(ansible_distribution_release) }}-prod main
  register: __cvmfs_apt_respository_result

- name: Update apt cache after key changes
  ansible.builtin.apt:
    update_cache: yes
  when: __cvmfs_apt_respository_result is changed

- name: Install CernVM-FS packages and dependencies (apt)
  ansible.builtin.apt:
    name: "{{ cvmfs_packages[_cvmfs_role] }}"
    state: "{{ 'latest' if _cvmfs_upgrade else 'present' }}"
