---

- name: Install apt dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates

- name: Install CernVM apt key
  apt_key:
    url: https://cvmrepo.web.cern.ch/cvmrepo/apt/cernvm.gpg

- name: Configure CernVM apt repository
  apt_repository:
    filename: "cernvm.list"
    mode: 422
    repo: "deb [allow-insecure=true] https://cvmrepo.web.cern.ch/cvmrepo/apt/ {{ ansible_distribution_release }}-prod main"
  when: ansible_distribution != 'Ubuntu'

- name: Configure CernVM apt repository
  apt_repository:
    filename: "cernvm.list"
    mode: 422
    repo: "deb [allow-insecure=true] https://cvmrepo.web.cern.ch/cvmrepo/apt/ {{ ansible_distribution_release }}-prod main"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release in ('bionic', 'xenial', 'precise')

  # There are no packages for any of the non LTS versions so good
  # luck and have fun if that's you.
- name: Configure CernVM apt repository
  apt_repository:
    filename: "cernvm.list"
    mode: 422
    repo: "deb [allow-insecure=true] https://cvmrepo.web.cern.ch/cvmrepo/apt/ xenial-prod main"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release not in ('bionic', 'xenial', 'precise')

- name: Install CernVM-FS packages and dependencies (apt)
  apt:
    name: "{{ cvmfs_packages[_cvmfs_role] }}"
    state: "{{ 'latest' if _cvmfs_upgrade else 'present' }}"
