---
- name: Install apt dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates

- name: Remove old CernVM GPG key from legacy keyring
  ansible.builtin.apt_key:
    url: https://cvmrepo.web.cern.ch/cvmrepo/apt/cernvm.gpg
    state: absent
  ignore_errors: true

- name: Download CernVM GPG key
  ansible.builtin.get_url:
    url: https://cvmrepo.web.cern.ch/cvmrepo/apt/cernvm.gpg
    dest: /usr/share/keyrings/cernvm.gpg
    mode: '0644'

- name: Configure CernVM apt repository
  ansible.builtin.apt_repository:
    filename: cernvm
    mode: 422
    repo: deb [signed-by=/usr/share/keyrings/cernvm.gpg] https://cvmrepo.web.cern.ch/cvmrepo/apt/ {{ ansible_distribution_release }}-prod main
  when: ansible_distribution != 'Ubuntu'

- name: Configure CernVM apt repository
  ansible.builtin.apt_repository:
    filename: cernvm
    mode: 422
    repo: deb [signed-by=/usr/share/keyrings/cernvm.gpg] https://cvmrepo.web.cern.ch/cvmrepo/apt/ {{ ansible_distribution_release }}-prod main
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release in ('bionic', 'xenial', 'precise', 'focal', 'jammy', 'noble')

# There are no packages for any of the non LTS versions so good
# luck and have fun if that's you.
- name: Configure CernVM apt repository
  ansible.builtin.apt_repository:
    filename: cernvm
    mode: 422
    repo: deb [signed-by=/usr/share/keyrings/cernvm.gpg] https://cvmrepo.web.cern.ch/cvmrepo/apt/ xenial-prod main
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release not in ('bionic', 'xenial', 'precise', 'focal', 'jammy', 'noble')

- name: Update apt cache after key changes
  ansible.builtin.apt:
    update_cache: yes

- name: Install CernVM-FS packages and dependencies (apt)
  ansible.builtin.apt:
    name: "{{ cvmfs_packages[_cvmfs_role] }}"
    state: "{{ 'latest' if _cvmfs_upgrade else 'present' }}"
